### ISSUE TITLE
alr publish failed precondition from alire-publish.adb:456

### ISSUE THREAD

**Issue by stcarrez** [alire-project/alire#593] opened 2020-10-25 18:00 UTC
When trying to use the new `alr publish` command, I'm getting an error:

```
$ alr publish -d --skip-build
✓ Local repository is clean.
✓ Revision exists in local repository (dc4fed79c381ac86154362b231b65da2e1012fb3).
warn: Private git git@github.com:stcarrez/ada-el.git transformed to public https://github.com/stcarrez/ada-el.git

Publishing assistant: step 1 of 6: Verify origin URL
✓ Origin is of supported kind: GIT
✓ Origin is hosted on trusted site: github.com

Publishing assistant: step 2 of 6: Verify GitHub infrastructure
✓ User has a GitHub account: stcarrez
✓ User has forked the community repository
✓ User's fork contains base branch: stable-0.4

Publishing assistant: step 3 of 6: Deploy sources
Cloning into 'alr-jfcd.tmp'...
remote: Enumerating objects: 156, done.
remote: Counting objects: 100% (156/156), done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 1948 (delta 86), reused 110 (delta 49), pack-reused 1792
Receiving objects: 100% (1948/1948), 879.42 KiB | 2.08 MiB/s, done.
Resolving deltas: 100% (1366/1366), done.

Publishing assistant: step 4 of 6: Build release
warn: Build check skipped.

Publishing assistant: step 5 of 6: User review
stderr: SYSTEM.ASSERTIONS.ASSERT_FAILURE
stderr: failed precondition from alire-publish.adb:456
stderr: raised SYSTEM.ASSERTIONS.ASSERT_FAILURE : failed precondition from alire-publish.adb:456
[/opt/applications/gnat-2020/bin/alr]
System.Assertions.Raise_Assert_Failure at s-assert.adb:46
Alire.Publish.Show_And_Confirm at alire-publish.adb:456
Alire.Publish.Start_At at alire-publish.adb:722
Alire.Publish.Remote_Origin at alire-publish.adb:880
Alire.Publish.Local_Repository at alire-publish.adb:822
Alr.Commands.Publish.Execute at alr-commands-publish.adb:47
Alr.Commands.Execute_By_Name at alr-commands.adb:745
Alr.Commands.Execute at alr-commands.adb:715
Alr.Main at alr-main.adb:28
Main at b__alr-main.adb:1851
[/lib/x86_64-linux-gnu/libc.so.6]
0x7faf8674f0b1
[/opt/applications/gnat-2020/bin/alr]
0x43052c _start at ???
0xfffffffffffffffe

error: failed precondition from alire-publish.adb:456
error: alr encountered an unexpected error, re-run with -d for details.

```

Looking at the pre-condition in the source, it is not clear what caused the issue.

There seem to be a lot of magic behind the `alr publish` command.

**Comment by mosteo** [comment] 2020-10-25 18:11
Thanks for the report, Stephane. I suspect this is caused by the remote repository/source file not containing the `alire.toml` file. Definitely something we should report without crashing.

**Comment by stcarrez** [comment] 2020-10-25 18:13
@mosteo, yes that was the issue, the file was present locally but not committed in git.

**Comment by mosteo** [comment] 2020-10-26 19:06
Duplicate of #569

**Closed as completed** 2020-10-27 11:45 UTC
