### ISSUE TITLE
alr doesn't work with non-english locale.

### ISSUE THREAD

**Issue by reznikmm** [alire-project/alire#224] opened 2019-10-19 08:45 UTC
alr fails to find `make` while running with `LANG=ru_RU.UTF-8`.

```
$ alr get -v make
-> alr build is (OUTSIDE) (0 releases indexed) (loaded in 0.000s)
-> get:
-> Found 1 indexes
-> Found 1 indexes
-> Loading index found at /home/max/.config/alire/indexes/community/repo/index/index.toml
-> Loading full catalog from /home/max/.config/alire/indexes/community/repo/index
ERROR: The requested version (make=0.0.0) is not available
ERROR: You can retrieve it without dependencies with --only
ERROR: alr get unsuccessful
```

After `export LANG=C` it works fine.

**Comment by mosteo** [comment] 2019-10-19 09:51
I can reproduce, it's tied to current native package management. Since that part is going to be reworked this will be addressed at that time.

Once #222 is merged this should not be a blocker; users will get a warning instead.

Root cause: apt-cache reports in Russian and a pattern match fails:
```
$ apt-cache -q policy make
make:
  Установлен: 4.1-9.1ubuntu1
  Кандидат:   4.1-9.1ubuntu1
```

**Closed** 2020-03-20 17:48 UTC
Labels: bug
