### ISSUE TITLE
Constraint error when running alr update using Alire 1.1.0

### ISSUE THREAD

**Issue by timlag1305** [alire-project/alire#865] opened 2021-09-22 05:56 UTC
I recently tried running `alr update` using alire version 1.1.0 on Linux. I see the following constraint error before it provides a selection prompt for gprbuild. If I select gnat_native instead of gnat_external, this error doesn't occur. I didn't compile with debug information so I the stack trace isn't very useful. I can try recompiling with that information. In case that debug info isn't needed, I provided the error below.

```
$ alr update -d
Welcome to the toolchain selection assistant

In this assistant you can set up the default toolchain to be used with any crate
that does not specify its own top-level dependency on a version of gnat or 
gprbuild.

If you choose "None", Alire will use whatever version is found in the 
environment.

ⓘ gnat is currently not configured. (alr will use the version found in the environment.)

Please select the gnat version for use with this configuration
  1. gnat_native=11.2.1
  2. None
  3. gnat_external=11.1.0 [Detected at /usr/bin/gnat]
  4. gnat_arm_elf=11.2.1
  5. gnat_riscv64_elf=11.2.1
  6. gnat_arm_elf=10.3.1
  7. gnat_native=10.3.1
  8. gnat_riscv64_elf=10.3.1
Enter your choice index (first is default): 
> 3
ⓘ Selected tool version gnat_external=11.1.0

ⓘ Choices for the following tool are narrowed down to releases compatible with just selected gnat_external=11.1.0

ⓘ gprbuild is currently not configured. (alr will use the version found in the environment.)

stderr: CONSTRAINT_ERROR                    
stderr: AAA.Strings.Vectors.Insert: Before index is out of range (too large)
stderr: raised CONSTRAINT_ERROR : AAA.Strings.Vectors.Insert: Before index is out of range (too large)
0x5583e2d18a2a
0x5583e2b2736e
0x5583e2b2b766
0x5583e2b0f66d
0x5583e22fcae7
0x5583e22b0e26
0x5583e22f49d7
0x5583e22fe67c
0x5583e21faaaa
0x5583e21fd5c2
[/usr/bin/..//lib/libc.so.6]
0x7f2f94330b23
0x5583e21fa64c
0xfffffffffffffffe

error: AAA.Strings.Vectors.Insert: Before index is out of range (too large)
error: alr encountered an unexpected error, re-run with -d for details.
```

**Comment by mosteo** [comment] 2021-09-22 09:01
Thanks for the report, Tim. Don't worry about the stack trace because I've seen this before (I thought it was fixed). As a workaround in your case, if you're going to use the external toolchain, you can simply choose None or disable the assistant entirely with `alr toolchain --disable-assistant`.

**Comment by mosteo** [comment] 2021-09-22 10:51
I've been able to reproduce it. My guess is that you have `gnat` installed from your distro packages but not `gprbuild`. Installing it should also allow you to run the assistant.

**Comment by mosteo** [comment] 2021-09-22 16:38
Manually cherry-picked into `master` after merging into `1.1`, so closing.

**Closed as completed by mosteo** 2021-09-22 16:38 UTC
